### ISSUE TITLE
Exception in Thread - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by coolacid** [logstash-plugins/logstash-input-irc#2]
Exception in thread "Ruby-0-Thread-214908: /opt/logstash/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/irc.rb:151" java.util.ConcurrentModificationException
        at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:882)
        at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:915)
        at org.jruby.RubyThreadGroup.list(RubyThreadGroup.java:149)
        at org.jruby.RubyThreadGroup$INVOKER$i$0$0$list.call(RubyThreadGroup$INVOKER$i$0$0$list.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:280)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.Cinch::Handler$$call_2c233db0803f6ad944be36fd2a93eac4795c766d1623409844.block_0$RUBY$**file**(/opt/logstash/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/handler.rb:93)
        at rubyjit$Cinch::Handler$$call_2c233db0803f6ad944be36fd2a93eac4795c766d1623409844$block_0$RUBY$**file**.call(rubyjit$Cinch::Handler$$call_2c233db0803f6ad944be36fd2a93eac4795c766d1623409844$block_0$RUBY$**file**)
        at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:159)
        at org.jruby.runtime.CompiledBlock19.call(CompiledBlock19.java:87)
        at org.jruby.runtime.Block.call(Block.java:101)
        at org.jruby.RubyProc.call(RubyProc.java:290)
        at org.jruby.RubyProc.call(RubyProc.java:228)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jrgns** [comment]
I'm seeing this as well. Logstash will process 10 messages and then throw this.

Edit: it seems this only happens if the `catch_all` option is enabled.
