### ISSUE TITLE
Exception: Cinch::Exceptions::SyncedAttributeNotAvailable

### ISSUE THREAD

**Issue by ycombinator** [logstash-plugins/logstash-input-irc#9]
Turns out that if you run logstash with this plugin for > 10 minutes or so, you'll start seeing errors like this:

```
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Irc channels=>["##elk_dr", "#logstash", "#elasticsearch", "#kibana", "#elastic-webinar"], host=>"irc.freenode.net", nick=>"SKTestIrcBot", real=>"Ask @elastic", type=>"irc", user=>"logstash">
  Error: 'host' for #<User nick="matflores">
  Exception: Cinch::Exceptions::SyncedAttributeNotAvailable
  Stack: /usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/syncable.rb:21:in `wait_until_synced'
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/syncable.rb:67:in `attr'
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/user.rb:234:in `attr'
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/user.rb:51:in `host'
/etc/logstash/plugins/logstash/inputs/irc.rb:137:in `handle_response'
/usr/local/logstash/logstash-1.4.2/lib/logstash/codecs/plain.rb:36:in `decode'
/etc/logstash/plugins/logstash/inputs/irc.rb:130:in `handle_response'
/etc/logstash/plugins/logstash/inputs/irc.rb:103:in `run'
org/jruby/RubyKernel.java:1521:in `loop'
/etc/logstash/plugins/logstash/inputs/irc.rb:101:in `run'
/usr/local/logstash/logstash-1.4.2/lib/logstash/pipeline.rb:163:in `inputworker'
/usr/local/logstash/logstash-1.4.2/lib/logstash/pipeline.rb:157:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"168"}
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/syncable.rb:21:in `wait_until_synced'
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/syncable.rb:67:in `attr'
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/user.rb:234:in `attr'
/usr/local/logstash/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/cinch-2.1.0/lib/cinch/user.rb:51:in `host'
/etc/logstash/plugins/logstash/inputs/irc.rb:137:in `handle_response'
/usr/local/logstash/logstash-1.4.2/lib/logstash/codecs/plain.rb:36:in `decode'
/etc/logstash/plugins/logstash/inputs/irc.rb:130:in `handle_response'
/etc/logstash/plugins/logstash/inputs/irc.rb:103:in `run'
org/jruby/RubyKernel.java:1521:in `loop'
/etc/logstash/plugins/logstash/inputs/irc.rb:101:in `run'
/usr/local/logstash/logstash-1.4.2/lib/logstash/pipeline.rb:163:in `inputworker'
/usr/local/logstash/logstash-1.4.2/lib/logstash/pipeline.rb:157:in `start_input'
```

**Comment by ycombinator** [comment]
I'm pretty sure this is due to the change made in https://github.com/logstash-plugins/logstash-input-irc/commit/26a778ed9164186436485aa225519ab99f10859d but I'm testing without that change to confirm if the error goes away.

**Comment by ycombinator** [comment]
Confirmed. I've been running LS with this plugin for nearly 90 minutes without the error showing up. I'll submit a PR to remove the offending line.
